// Seed script — inserts initial data into Supabase (using actual auth user IDs)
const SUPABASE_URL = 'https://bkhglsjtyplqeslmswkm.supabase.co'
const SERVICE_ROLE_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJraGdsc2p0eXBscWVzbG1zd2ttIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3ODUxMjYzMSwiZXhwIjoyMDk0MDg4NjMxfQ.UQg_dieipF23mK4eXe431JdgkhRonB8otusBOB81CAc'

// Actual IDs from Supabase auth
const LIWEI = 'b0a39813-70e7-4ae5-bc60-2c2b714b7dc0'
const CHENYU = '70ed6d50-1329-4f56-8fe5-bd6ef3d048b7'
const WANGFANG = 'b53dadc0-8b71-436d-a729-28cfe3ec46b5'
const ZHANGMEI = '55a83879-7f5f-40ec-b399-9ff493e763a5'
const LIUYANG = '54c263c8-7f1b-43fe-b45c-08fd86999ced'
const ZHAOTING = '7035232e-cc14-499c-b1bb-8c8fbcd267f7'

async function main() {
  const { createClient } = await import('@supabase/supabase-js')
  const supabase = createClient(SUPABASE_URL, SERVICE_ROLE_KEY, {
    auth: { autoRefreshToken: false, persistSession: false }
  })

  console.log('🚀 Seeding with actual user IDs...\n')

  // Step 1: Update profiles (trigger already created them)
  console.log('Step 1: Updating profiles...')
  const profileUpdates = [
    { id: LIWEI, display_name: 'Li Wei', avatar_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&h=200&fit=crop&crop=face', role: 'guide', bio: "Born and raised in Beijing's historic hutongs, I've spent 8 years sharing the soul of China's capital with travelers from around the world. My tours go beyond the Great Wall — I'll take you to hidden courtyards, century-old noodle shops, and sunrise spots most tourists never find.", country: 'China', language: ['en', 'zh'] },
    { id: CHENYU, display_name: 'Chen Yu', avatar_url: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&h=200&fit=crop&crop=face', role: 'guide', bio: "A landscape photographer turned guide, I specialize in the breathtaking karst mountains of Guilin and Yangshuo. Whether it's a sunrise hike above the Li River or cycling through rice terraces, I'll help you capture China's most iconic scenery.", country: 'China', language: ['en', 'zh'] },
    { id: WANGFANG, display_name: 'Wang Fang', avatar_url: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=200&h=200&fit=crop&crop=face', role: 'guide', bio: "Xi'an is my home and my passion. With a degree in Chinese history and 6 years of guiding experience, I bring the Silk Road, the Terracotta Army, and the Tang Dynasty to life. I speak English, Chinese, and conversational Japanese.", country: 'China', language: ['en', 'zh', 'ja'] },
    { id: ZHANGMEI, display_name: 'Zhang Mei', avatar_url: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&h=200&fit=crop&crop=face', role: 'guide', bio: "Shanghai is where tradition meets tomorrow. I'm a foodie, a night owl, and your ultimate guide to this dazzling metropolis. From soup dumplings in hidden alleyways to rooftop bars overlooking the Bund, I know every corner of this city.", country: 'China', language: ['en', 'zh'] },
    { id: LIUYANG, display_name: 'Liu Yang', avatar_url: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=200&h=200&fit=crop&crop=face', role: 'guide', bio: "Chengdu is not just pandas — it's a lifestyle. I'll take you to bamboo forests where giant pandas roam, tea houses where time stands still, and spicy hotpot joints that will change your life. Come hungry and curious.", country: 'China', language: ['en', 'zh'] },
    { id: ZHAOTING, display_name: 'Zhao Ting', avatar_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&h=200&fit=crop&crop=face', role: 'guide', bio: "Hangzhou is poetry in motion. I guide travelers through misty West Lake mornings, ancient tea plantations, and poetic pagodas that inspired centuries of Chinese literature. I also speak French — bienvenue!", country: 'China', language: ['en', 'zh', 'fr'] },
  ]

  for (const p of profileUpdates) {
    const { error } = await supabase.from('profiles').update({
      display_name: p.display_name, avatar_url: p.avatar_url, role: p.role,
      bio: p.bio, country: p.country, language: p.language
    }).eq('id', p.id)
    console.log(`  ${error ? '❌' : '✅'} ${p.display_name}`)
  }

  // Step 2: Upsert guide_profiles
  console.log('\nStep 2: Upserting guide_profiles...')
  const guideProfiles = [
    { id: LIWEI, certification_type: 'individual', real_name: '李伟', specialties: ['Culture', 'History', 'Food'], languages_spoken: ['English', 'Chinese'], service_cities: ['Beijing', 'Tianjin'], years_experience: 8, verification_status: 'verified', intro: "Beijing hutong explorer — showing you the soul of the capital beyond the tourist traps.", gallery_urls: ['https://images.unsplash.com/photo-1508804185872-d7badad00f7d?w=600', 'https://images.unsplash.com/photo-1547981609-4b6bfe67ca0b?w=600', 'https://images.unsplash.com/photo-1599707367812-042bfd7e5794?w=600'] },
    { id: CHENYU, certification_type: 'individual', real_name: '陈宇', specialties: ['Nature', 'Hiking', 'Photography'], languages_spoken: ['English', 'Chinese'], service_cities: ['Guilin', 'Yangshuo', 'Longsheng'], years_experience: 5, verification_status: 'verified', intro: "Landscape photographer turned guide — I'll take you to China's most photogenic spots.", gallery_urls: ['https://images.unsplash.com/photo-1528164344705-47542687000d?w=600', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?w=600', 'https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?w=600'] },
    { id: WANGFANG, certification_type: 'individual', real_name: '王芳', specialties: ['History', 'Architecture', 'Silk Road'], languages_spoken: ['English', 'Chinese', 'Japanese'], service_cities: ["Xi'an", 'Dunhuang', 'Luoyang'], years_experience: 6, verification_status: 'verified', intro: 'History degree + 6 years guiding — bringing the Silk Road and Tang Dynasty back to life.', gallery_urls: ['https://images.unsplash.com/photo-1555990538-1e15b0e8b558?w=600', 'https://images.unsplash.com/photo-1536098561742-ca998e48cbcc?w=600', 'https://images.unsplash.com/photo-1503899036084-c55cdd92da26?w=600'] },
    { id: ZHANGMEI, certification_type: 'individual', real_name: '张美', specialties: ['Food', 'Nightlife', 'Shopping'], languages_spoken: ['English', 'Chinese'], service_cities: ['Shanghai', 'Suzhou', 'Hangzhou'], years_experience: 4, verification_status: 'verified', intro: 'Shanghai foodie & night owl — from hidden soup dumpling spots to Bund rooftop bars.', gallery_urls: ['https://images.unsplash.com/photo-1537531383496-f4749b08f3ba?w=600', 'https://images.unsplash.com/photo-1474181487882-5abf3f0ba6c2?w=600', 'https://images.unsplash.com/photo-1536599018102-9f803c140fc1?w=600'] },
    { id: LIUYANG, certification_type: 'individual', real_name: '刘洋', specialties: ['Wildlife', 'Food', 'Tea Culture'], languages_spoken: ['English', 'Chinese'], service_cities: ['Chengdu', 'Leshan', 'Emeishan'], years_experience: 7, verification_status: 'verified', intro: "Panda whisperer & tea connoisseur — Chengdu is not just a city, it's a lifestyle.", gallery_urls: ['https://images.unsplash.com/photo-1564349683136-77e08dba1ef7?w=600', 'https://images.unsplash.com/photo-1551918120-9739cb430c6d?w=600', 'https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=600'] },
    { id: ZHAOTING, certification_type: 'individual', real_name: '赵婷', specialties: ['Culture', 'Photography', 'Cycling'], languages_spoken: ['English', 'Chinese', 'French'], service_cities: ['Hangzhou', 'Suzhou', 'Shaoxing'], years_experience: 3, verification_status: 'verified', intro: "West Lake sunrise chaser — guiding you through China's most poetic landscapes.", gallery_urls: ['https://images.unsplash.com/photo-1529240168534-2b0f59b671b0?w=600', 'https://images.unsplash.com/photo-1480796927426-f609979314bd?w=600', 'https://images.unsplash.com/photo-1509909756405-be0199881695?w=600'] },
  ]

  const { error: gpErr } = await supabase.from('guide_profiles').upsert(guideProfiles, { onConflict: 'id' })
  if (gpErr) console.log(`  ❌ ${gpErr.message}`)
  else console.log(`  ✅ ${guideProfiles.length} guide_profiles`)

  // Step 3: Insert tour_plans
  console.log('\nStep 3: Inserting tour_plans...')
  const plans = [
    { id: 'f1a2b3c4-0001-4000-a000-000000000001', guide_id: LIWEI, title: 'Classic Beijing — Imperial Grandeur', subtitle: '3 days of emperors, hutongs & the Great Wall', description: "Discover Beijing's imperial splendor and local charm. Walk through the Forbidden City at golden hour, get lost in hutong alleyways, and watch sunrise paint the Great Wall gold. This is the Beijing most tourists miss.", cover_image_url: 'https://images.unsplash.com/photo-1508804185872-d7badad00f7d?w=800', gallery_urls: ['https://images.unsplash.com/photo-1547981609-4b6bfe67ca0b?w=800', 'https://images.unsplash.com/photo-1599707367812-042bfd7e5794?w=800', 'https://images.unsplash.com/photo-1584450150502-2795e9d0f662?w=800'], destinations: [{city:'Beijing',spots:['Forbidden City','Jingshan Park','Nanluoguxiang']},{city:'Beijing',spots:['Mutianyu Great Wall','Hutong Courtyard']},{city:'Beijing',spots:['Temple of Heaven','Panjiayuan Market']}], itinerary: [{day:1,title:'Imperial Heart of Beijing',description:'Enter the Forbidden City through the Meridian Gate, climb Jingshan for a panoramic view, then wander Nanluoguxiang hutong for local snacks and crafts.',spots:['Forbidden City','Jingshan Park','Nanluoguxiang'],meals:{lunch:'Traditional Beijing noodles',dinner:'Peking Duck at a century-old restaurant'}},{day:2,title:'Sunrise at the Great Wall',description:'Early departure to Mutianyu — less crowded, more spectacular. Cable car up, toboggan down. Afternoon tea in a restored hutong courtyard.',spots:['Mutianyu Great Wall','Hutong Courtyard'],meals:{lunch:'Farmhouse feast near the Wall',dinner:'Hotpot in a hidden courtyard'}},{day:3,title:'Temple, Tea & Treasures',description:'Morning tai chi at Temple of Heaven, explore the Echo Wall. Afternoon at Panjiayuan antiques market — the real one, not the tourist trap.',spots:['Temple of Heaven','Panjiayuan Market'],meals:{lunch:'Dim sum brunch',dinner:'Farewell banquet'}}], duration_days: 3, max_group_size: 8, price_cny: 3200, currency: 'CNY', price_breakdown: {accommodation:1200,meals:800,transport:500,guide_fee:700}, includes: ['English-speaking guide','Private transport','2 nights boutique hotel','All entrance fees','All meals','Great Wall cable car'], excludes: ['International flights','Travel insurance','Personal expenses','Tips'], highlights: ['Forbidden City golden hour tour','Sunrise at Mutianyu Great Wall','Hidden hutong courtyard visit','Peking Duck at a century-old restaurant'], tags: ['Beijing','Great Wall','Forbidden City','Culture','History'], difficulty: 'easy', status: 'published', view_count: 3200, booking_count: 156 },
    { id: 'f1a2b3c4-0002-4000-a000-000000000002', guide_id: LIWEI, title: "Hidden Beijing — A Foodie's Pilgrimage", subtitle: '2 days of legendary street food & secret kitchens', description: "Forget the restaurants in guidebooks. This tour takes you through Beijing's underground food scene — from 5am breakfast markets to midnight lamb skewer alleys. Come hungry, leave changed.", cover_image_url: 'https://images.unsplash.com/photo-1547981609-4b6bfe67ca0b?w=800', gallery_urls: ['https://images.unsplash.com/photo-1508804185872-d7badad00f7d?w=800','https://images.unsplash.com/photo-1584450150502-2795e9d0f662?w=800'], destinations: [{city:'Beijing',spots:['Qianmen Street','Guijie (Ghost Street)','Hutong Kitchens']},{city:'Beijing',spots:['Panjiayuan Breakfast','Temple of Heaven','Wangfujing']}], itinerary: [{day:1,title:'Street Food Marathon',description:"Start at Qianmen for jianbing and soy milk. Walk through hutongs tasting zhajiangmian, tanghulu, and baozi. Dinner on Ghost Street — Beijing's legendary midnight food street.",spots:['Qianmen Street','Guijie (Ghost Street)','Hutong Kitchens'],meals:{lunch:'Hutong noodle crawl',dinner:'Ghost Street seafood feast'}},{day:2,title:'Morning Markets to Imperial Treats',description:'5am Panjiayuan breakfast with the locals. Then imperial-style pastries at a 200-year-old shop. Afternoon tea ceremony with Beijing snacks.',spots:['Panjiayuan Breakfast','Temple of Heaven','Wangfujing'],meals:{lunch:'Imperial court cuisine',dinner:'Farewell hotpot'}}], duration_days: 2, max_group_size: 6, price_cny: 1800, currency: 'CNY', price_breakdown: {meals:900,guide_fee:500,transport:400}, includes: ['English-speaking guide','All food tastings','Private transport','Tea ceremony'], excludes: ['Accommodation','International flights','Alcoholic drinks','Tips'], highlights: ['Ghost Street midnight food crawl','200-year-old imperial pastry shop','Hidden hutong kitchen access','Traditional tea ceremony'], tags: ['Beijing','Food','Street Food','Culture'], difficulty: 'easy', status: 'published', view_count: 2100, booking_count: 89 },
    { id: 'f1a2b3c4-0003-4000-a000-000000000003', guide_id: CHENYU, title: 'Guilin & Yangshuo — Through the Lens', subtitle: '4 days of karst peaks, rice terraces & river sunrises', description: "China's most photographed landscape, guided by a professional photographer. Sunrise over the Li River, golden hour at Longji rice terraces, and moonlit cycling through Yangshuo. Your Instagram will never be the same.", cover_image_url: 'https://images.unsplash.com/photo-1528164344705-47542687000d?w=800', gallery_urls: ['https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?w=800','https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?w=800'], destinations: [{city:'Guilin',spots:['Elephant Trunk Hill','Reed Flute Cave']},{city:'Li River',spots:['Xingping','Yellow Cloth Shoal']},{city:'Yangshuo',spots:['Moon Hill','Yulong River']},{city:'Longsheng',spots:['Longji Rice Terraces']}], itinerary: [{day:1,title:'Guilin City Sights',description:'Arrive in Guilin, photograph Elephant Trunk Hill at sunset, explore the magical Reed Flute Cave with its neon-lit stalactites.',spots:['Elephant Trunk Hill','Reed Flute Cave'],meals:{dinner:'Guilin rice noodles'}},{day:2,title:'Li River Sunrise',description:'Pre-dawn boat to Xingping — the 20 yuan bill viewpoint. Photograph cormorant fishermen at sunrise. Afternoon bamboo raft on the Yulong River.',spots:['Xingping','Yellow Cloth Shoal','Yulong River'],meals:{lunch:'River fish feast',dinner:'Yangshuo beer fish'}},{day:3,title:'Yangshuo Adventures',description:'Cycle through karst valleys, photograph Moon Hill, sunset at the Big Banyan Tree. Evening at the Impression Sanjie Liu light show.',spots:['Moon Hill','Yulong River','Impression Sanjie Liu'],meals:{lunch:'Countryside farmhouse',dinner:'West Street food crawl'}},{day:4,title:'Longji Rice Terraces',description:'Drive to Longji, hike through layered rice terraces. Photograph the Dragons Backbone at golden hour before heading back.',spots:['Longji Rice Terraces'],meals:{lunch:'Zhuang minority cuisine',dinner:'Farewell dinner in Guilin'}}], duration_days: 4, max_group_size: 6, price_cny: 4100, currency: 'CNY', price_breakdown: {accommodation:1400,meals:1000,transport:800,guide_fee:900}, includes: ['Photography guide','Private transport','3 nights hotel','All meals','Li River boat','Bamboo raft','Longji entrance fees'], excludes: ['International flights','Camera equipment','Travel insurance','Tips'], highlights: ['Li River sunrise from the 20-yuan viewpoint','Cormorant fishermen photography session','Longji Rice Terraces at golden hour','Impression Sanjie Liu light show'], tags: ['Guilin','Yangshuo','Photography','Nature','Hiking'], difficulty: 'moderate', status: 'published', view_count: 4100, booking_count: 201 },
    { id: 'f1a2b3c4-0004-4000-a000-000000000004', guide_id: CHENYU, title: "Zhangjiajie — Avatar's Floating Mountains", subtitle: '3 days among the pillars that inspired Pandora', description: "Walk among the sandstone pillars that floated in Avatar. Glass bridges, cloud-sea viewpoints, and the world's tallest outdoor elevator. This is China's most otherworldly landscape.", cover_image_url: 'https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?w=800', gallery_urls: ['https://images.unsplash.com/photo-1528164344705-47542687000d?w=800','https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?w=800'], destinations: [{city:'Zhangjiajie',spots:['Zhangjiajie National Forest Park','Golden Whip Stream']},{city:'Zhangjiajie',spots:['Yuanjiajie (Avatar Hallelujah Mountain)','Bailong Elevator']},{city:'Zhangjiajie',spots:['Tianmen Mountain','Glass Skywalk']}], itinerary: [{day:1,title:'Enter the Forest of Pillars',description:"Hike Golden Whip Stream through towering sandstone columns. Afternoon at Zhangjiajie National Forest Park — the inspiration for Avatar's floating mountains.",spots:['Zhangjiajie National Forest Park','Golden Whip Stream'],meals:{lunch:'Mountain picnic',dinner:'Tujia minority cuisine'}},{day:2,title:'Avatar Hallelujah Mountain',description:'Take the Bailong Elevator (326m!) to Yuanjiajie. Stand where Avatar was conceived. Cross the First Bridge Under Heaven. Afternoon photography at Tianzi Mountain.',spots:['Yuanjiajie','Bailong Elevator','Tianzi Mountain'],meals:{lunch:'Mountain restaurant',dinner:'Local hotpot'}},{day:3,title:'Tianmen Mountain & The Gate to Heaven',description:"Ride the world's longest cable car to Tianmen Mountain. Walk the glass skywalk clinging to the cliff. Descend through Tianmen Cave — the natural arch known as Heaven's Gate.",spots:['Tianmen Mountain','Glass Skywalk','Tianmen Cave'],meals:{lunch:'Cliffside restaurant',dinner:'Farewell dinner'}}], duration_days: 3, max_group_size: 8, price_cny: 4500, currency: 'CNY', price_breakdown: {accommodation:1200,meals:800,transport:600,guide_fee:800,tickets:1100}, includes: ['Photography guide','Private transport','2 nights hotel','All meals','All park entrance fees','Bailong Elevator','Cable car tickets'], excludes: ['International flights','Travel insurance','Personal expenses','Tips'], highlights: ["Bailong Elevator — world's tallest outdoor elevator",'Avatar Hallelujah Mountain viewpoint',"Tianmen Cave — Heaven's Gate",'Glass skywalk on Tianmen Mountain'], tags: ['Zhangjiajie','Avatar','Nature','Adventure','Photography'], difficulty: 'moderate', status: 'published', view_count: 4500, booking_count: 234 },
    { id: 'f1a2b3c4-0005-4000-a000-000000000005', guide_id: WANGFANG, title: "Xi'an — Echoes of the Silk Road", subtitle: '3 days of terracotta warriors, city walls & Tang Dynasty nights', description: "Walk the same streets as Silk Road merchants 2,000 years ago. Stand face-to-face with 8,000 terracotta soldiers. Cycle atop China's best-preserved city wall at sunset. Xi'an is where Chinese civilization began.", cover_image_url: 'https://images.unsplash.com/photo-1555990538-1e15b0e8b558?w=800', gallery_urls: ['https://images.unsplash.com/photo-1536098561742-ca998e48cbcc?w=800','https://images.unsplash.com/photo-1503899036084-c55cdd92da26?w=800'], destinations: [{city:"Xi'an",spots:['Terracotta Army','Huaqing Palace']},{city:"Xi'an",spots:['Ancient City Wall','Muslim Quarter','Bell Tower']},{city:"Xi'an",spots:['Shaanxi History Museum','Big Wild Goose Pagoda','Tang Dynasty Show']}], itinerary: [{day:1,title:'The Terracotta Army',description:'Morning visit to the pit where 8,000 warriors stood guard for 2,200 years. Each face is unique. Afternoon at Huaqing Palace — hot springs of the legendary Yang Guifei.',spots:['Terracotta Army','Huaqing Palace'],meals:{lunch:'Biangbiang noodles',dinner:'Muslim Quarter street food'}},{day:2,title:'Walls, Bells & Barbecue',description:"Cycle the 14km ancient city wall at golden hour. Explore the Muslim Quarter's bustling food scene. Evening view from the Bell Tower lit up at night.",spots:['Ancient City Wall','Muslim Quarter','Bell Tower'],meals:{lunch:'Roujiamo (Chinese hamburger)',dinner:"Xi'an BBQ feast"}},{day:3,title:'Tang Dynasty Splendor',description:'Explore Shaanxi History Museum — 3,700 years of artifacts. Afternoon at Big Wild Goose Pagoda. Evening Tang Dynasty music and dance show with a royal banquet.',spots:['Shaanxi History Museum','Big Wild Goose Pagoda','Tang Dynasty Show'],meals:{lunch:'Dumpling banquet',dinner:'Tang Dynasty royal banquet'}}], duration_days: 3, max_group_size: 10, price_cny: 3600, currency: 'CNY', price_breakdown: {accommodation:1100,meals:900,transport:500,guide_fee:600,tickets:500}, includes: ['English-speaking guide','Private transport','2 nights hotel','All meals','Terracotta Army tickets','City Wall bike rental','Tang Dynasty show tickets'], excludes: ['International flights','Travel insurance','Personal expenses','Tips'], highlights: ['Face-to-face with 8,000 Terracotta Warriors','Sunset cycling on the Ancient City Wall','Muslim Quarter food adventure','Tang Dynasty royal banquet & show'], tags: ["Xi'an",'Terracotta','Silk Road','History','Culture'], difficulty: 'easy', status: 'published', view_count: 3600, booking_count: 178 },
    { id: 'f1a2b3c4-0006-4000-a000-000000000006', guide_id: ZHANGMEI, title: 'Shanghai — Where Tradition Meets Tomorrow', subtitle: '2 days of skyline magic, hidden food & nightlife', description: "Shanghai is a city that never stops reinventing itself. I'll take you from 1920s art deco lanes to the world's most stunning skyline, with the best food stops in between. Day or night, this city delivers.", cover_image_url: 'https://images.unsplash.com/photo-1537531383496-f4749b08f3ba?w=800', gallery_urls: ['https://images.unsplash.com/photo-1474181487882-5abf3f0ba6c2?w=800','https://images.unsplash.com/photo-1536599018102-9f803c140fc1?w=800'], destinations: [{city:'Shanghai',spots:['The Bund','Yu Garden','French Concession']},{city:'Shanghai',spots:['Tianzifang','Lujiazui','Bar Rouge']}], itinerary: [{day:1,title:'Old Shanghai Soul',description:'Start at Yu Garden — a Ming Dynasty masterpiece hidden in the city. Walk the French Concession tree-lined streets. Sunset cocktails on the Bund watching Pudong light up.',spots:['The Bund','Yu Garden','French Concession'],meals:{lunch:'Xiaolongbao at the original Din Tai Fung',dinner:'Shanghainese braised pork & hairy crab'}},{day:2,title:'Future Shanghai',description:'Morning at Tianzifang art alley — galleries in old lilong lanes. Afternoon at the top of Shanghai Tower (632m). Night out on the town — rooftop bars with killer skyline views.',spots:['Tianzifang','Lujiazui','Bar Rouge'],meals:{lunch:'Hidden noodle shop in Tianzifang',dinner:'Rooftop dinner with Bund views'}}], duration_days: 2, max_group_size: 8, price_cny: 2800, currency: 'CNY', price_breakdown: {accommodation:800,meals:800,transport:400,guide_fee:500,tickets:300}, includes: ['English-speaking guide','Private transport','1 night boutique hotel','All meals','Shanghai Tower observation deck','Tea ceremony at Yu Garden'], excludes: ['International flights','Travel insurance','Alcoholic drinks','Tips'], highlights: ['Bund sunset cocktail with Pudong skyline','Shanghai Tower — 632m above the city','Hidden French Concession cafe crawl','Rooftop bar with killer night views'], tags: ['Shanghai','Nightlife','Food','Skyline','Modern China'], difficulty: 'easy', status: 'published', view_count: 2800, booking_count: 98 },
    { id: 'f1a2b3c4-0007-4000-a000-000000000007', guide_id: LIUYANG, title: 'Chengdu — Pandas, Tea & Burning Tongues', subtitle: '3 days of giant pandas, ancient tea houses & numbing spice', description: "Chengdu doesn't rush — and neither will you. Wake up with baby pandas, sip tea in a 100-year-old teahouse, then sweat through a Sichuan hotpot that will rewire your taste buds. This is the good life, Chinese style.", cover_image_url: 'https://images.unsplash.com/photo-1564349683136-77e08dba1ef7?w=800', gallery_urls: ['https://images.unsplash.com/photo-1551918120-9739cb430c6d?w=800','https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=800'], destinations: [{city:'Chengdu',spots:['Chengdu Research Base','Jinli Street','Sichuan Opera']},{city:'Chengdu',spots:["People's Park Teahouse",'Wenshu Monastery','Hotpot District']},{city:'Leshan',spots:['Leshan Giant Buddha','Qingyi River']}], itinerary: [{day:1,title:'Morning with Pandas',description:'Early access to the Panda Base before the crowds. Watch baby pandas tumble and adult pandas demolish bamboo. Evening at Jinli ancient street and Sichuan Opera face-changing show.',spots:['Chengdu Research Base','Jinli Street','Sichuan Opera'],meals:{lunch:"Mapo tofu at the original Chen's",dinner:'Sichuan hotpot challenge'}},{day:2,title:'Tea, Temples & Spice',description:"Morning at People's Park teahouse — Chengdu's living room. Afternoon at Wenshu Monastery for vegetarian lunch and incense. Evening hotpot that will change your life.",spots:["People's Park Teahouse",'Wenshu Monastery','Hotpot District'],meals:{lunch:'Monastery vegetarian feast',dinner:'Numbing & spicy hotpot experience'}},{day:3,title:'The Giant Buddha of Leshan',description:'Day trip to the 71m Giant Buddha carved into a cliff. Boat view from the river, then hike to stand at his toes. Farewell dinner back in Chengdu.',spots:['Leshan Giant Buddha','Qingyi River'],meals:{lunch:'Leshan sweet duck & bobo chicken',dinner:'Farewell Sichuan banquet'}}], duration_days: 3, max_group_size: 8, price_cny: 3400, currency: 'CNY', price_breakdown: {accommodation:1000,meals:900,transport:600,guide_fee:600,tickets:300}, includes: ['English-speaking guide','Private transport','2 nights hotel','All meals','Panda Base early access','Sichuan Opera tickets','Leshan boat ticket'], excludes: ['International flights','Travel insurance','Personal expenses','Tips'], highlights: ['Early access baby panda encounter','100-year-old teahouse experience','Sichuan face-changing opera','71m Leshan Giant Buddha from the river'], tags: ['Chengdu','Pandas','Sichuan Food','Tea','Culture'], difficulty: 'easy', status: 'published', view_count: 3400, booking_count: 167 },
    { id: 'f1a2b3c4-0008-4000-a000-000000000008', guide_id: ZHAOTING, title: 'Hangzhou — Poems on Water', subtitle: '3 days of misty lakes, dragon well tea & silk roads', description: 'Hangzhou has inspired Chinese poets for a thousand years. Cycle around West Lake at dawn, drink tea where emperors drank, and wander through bamboo forests that seem designed by an artist. This is China at its most beautiful.', cover_image_url: 'https://images.unsplash.com/photo-1529240168534-2b0f59b671b0?w=800', gallery_urls: ['https://images.unsplash.com/photo-1480796927426-f609979314bd?w=800','https://images.unsplash.com/photo-1509909756405-be0199881695?w=800'], destinations: [{city:'Hangzhou',spots:['West Lake','Lingyin Temple']},{city:'Hangzhou',spots:['Longjing Tea Village','Nine Creeks','Bamboo Forest']},{city:'Hangzhou',spots:['Hefang Street','China Silk Museum','Grand Canal']}], itinerary: [{day:1,title:'Misty West Lake & Ancient Temple',description:"Dawn walk along Su Causeway as mist rises off West Lake. Visit Lingyin Temple — one of China's oldest Buddhist temples with caves carved 1,600 years ago.",spots:['West Lake','Lingyin Temple'],meals:{lunch:'West Lake vinegar fish',dinner:"Dongpo pork & beggar's chicken"}},{day:2,title:'Dragon Well Tea & Bamboo Dreams',description:'Morning at Longjing Tea Village — pick and roast your own Dragon Well tea with a master. Afternoon hike through Nine Creeks and into bamboo forests straight out of Crouching Tiger.',spots:['Longjing Tea Village','Nine Creeks','Bamboo Forest'],meals:{lunch:'Tea-pairing lunch in the village',dinner:'Farmhouse dinner in the hills'}},{day:3,title:'Silk, Canals & Farewell',description:'Explore Hefang Street for traditional crafts. Visit the China Silk Museum to see how Hangzhou silk shaped world trade. Sunset boat ride on the Grand Canal — 2,500 years old and still flowing.',spots:['Hefang Street','China Silk Museum','Grand Canal'],meals:{lunch:'Silk Road-inspired feast',dinner:'Canalside farewell dinner'}}], duration_days: 3, max_group_size: 6, price_cny: 3000, currency: 'CNY', price_breakdown: {accommodation:1000,meals:800,transport:400,guide_fee:500,tickets:300}, includes: ['English-speaking guide','Private transport','2 nights hotel','All meals','Tea picking & roasting experience','Lingyin Temple tickets','Grand Canal boat ride'], excludes: ['International flights','Travel insurance','Personal expenses','Tips'], highlights: ['Dawn walk on Su Causeway through the mist','Pick and roast your own Dragon Well tea','Nine Creeks bamboo forest hike','Sunset on the 2,500-year-old Grand Canal'], tags: ['Hangzhou','Tea','Culture','Nature','Photography'], difficulty: 'easy', status: 'published', view_count: 3000, booking_count: 134 },
    { id: 'f1a2b3c4-0009-4000-a000-000000000009', guide_id: WANGFANG, title: 'Dunhuang — Gateway to the Silk Road', subtitle: '3 days of desert caves, camel caravans & starlit dunes', description: 'Stand where Silk Road caravans rested for thousands of years. Explore the Mogao Caves — 492 temples filled with 1,000 years of Buddhist art. Ride camels across singing sand dunes at sunset. Sleep under a billion stars in the Gobi Desert.', cover_image_url: 'https://images.unsplash.com/photo-1536098561742-ca998e48cbcc?w=800', gallery_urls: ['https://images.unsplash.com/photo-1555990538-1e15b0e8b558?w=800','https://images.unsplash.com/photo-1503899036084-c55cdd92da26?w=800'], destinations: [{city:'Dunhuang',spots:['Mogao Caves','Mingsha Shan']},{city:'Dunhuang',spots:['Yumen Pass','Yardang National Geopark']},{city:'Dunhuang',spots:['Crescent Lake','Shazhou Night Market']}], itinerary: [{day:1,title:'The Thousand Buddha Caves',description:'Morning at the legendary Mogao Caves — 492 cave temples with murals spanning 1,000 years. Afternoon sunset camel ride across Mingsha Shan singing sand dunes.',spots:['Mogao Caves','Mingsha Shan'],meals:{lunch:'Silk Road flatbread & lamb',dinner:'Desert campfire dinner'}},{day:2,title:'Jade Gate & the Wind City',description:'Drive to Yumen Pass — the gateway where Silk Road merchants entered the wilderness. Afternoon at Yardang National Geopark — wind-carved formations that look like an alien planet.',spots:['Yumen Pass','Yardang National Geopark'],meals:{lunch:'Picnic at Yumen Pass',dinner:'Uyghur cuisine in Dunhuang'}},{day:3,title:'Crescent Moon & Night Markets',description:'Morning at Crescent Lake — a desert oasis that has survived 2,000 years. Afternoon at Shazhou Night Market for silk, jade, and street food. Farewell under the desert stars.',spots:['Crescent Lake','Shazhou Night Market'],meals:{lunch:'Oasis-side noodles',dinner:'Farewell Silk Road feast'}}], duration_days: 3, max_group_size: 6, price_cny: 5200, currency: 'CNY', price_breakdown: {accommodation:1400,meals:1000,transport:1200,guide_fee:800,tickets:800}, includes: ['English-speaking guide','Private transport','2 nights hotel','All meals','Mogao Cave tickets','Camel ride','Desert camping experience'], excludes: ['International flights','Travel insurance','Personal expenses','Tips'], highlights: ['Mogao Caves — 1,000 years of Buddhist art','Sunset camel ride across singing sand dunes','Yardang — the alien planet on Earth','Stargazing in the Gobi Desert'], tags: ['Dunhuang','Silk Road','Desert','History','Adventure'], difficulty: 'moderate', status: 'published', view_count: 5200, booking_count: 89 },
    { id: 'f1a2b3c4-0010-4000-a000-000000000010', guide_id: LIUYANG, title: 'Emeishan — Summit of the Sacred', subtitle: '2 days of Buddhist peaks, monkey encounters & sea of clouds', description: "One of China's Four Sacred Buddhist Mountains. Hike through ancient forests, encounter wild monkeys, and reach the Golden Summit at 3,099m where clouds part to reveal a sea of gold. Spiritual, physical, unforgettable.", cover_image_url: 'https://images.unsplash.com/photo-1551918120-9739cb430c6d?w=800', gallery_urls: ['https://images.unsplash.com/photo-1564349683136-77e08dba1ef7?w=800','https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=800'], destinations: [{city:'Emeishan',spots:['Baoguo Temple','Qingyin Pavilion','Monkey Zone']},{city:'Emeishan',spots:['Golden Summit','Huazang Temple','Sea of Clouds']}], itinerary: [{day:1,title:'Temples & Monkeys',description:"Start at Baoguo Temple, hike through ancient forest to Qingyin Pavilion — where two streams meet in perfect harmony. Navigate the famous monkey zone (they're cheeky but fun).",spots:['Baoguo Temple','Qingyin Pavilion','Monkey Zone'],meals:{lunch:'Temple vegetarian lunch',dinner:'Monastery dinner'}},{day:2,title:'Golden Summit & Sea of Clouds',description:'Pre-dawn ascent to the Golden Summit at 3,099m. Watch the sun rise above a sea of clouds. Visit the golden statue of Samantabhadra. Descend through mossy trails.',spots:['Golden Summit','Huazang Temple','Sea of Clouds'],meals:{lunch:'Summit noodle soup',dinner:'Farewell dinner in Emeishan town'}}], duration_days: 2, max_group_size: 6, price_cny: 2400, currency: 'CNY', price_breakdown: {accommodation:600,meals:500,transport:400,guide_fee:500,tickets:400}, includes: ['English-speaking guide','Private transport','1 night temple lodge','All meals','Emeishan entrance tickets','Cable car tickets'], excludes: ['International flights','Travel insurance','Personal expenses','Tips'], highlights: ['Sunrise at the 3,099m Golden Summit','Wild monkey encounters on the trail','Temple lodge overnight experience','Sea of clouds from the summit'], tags: ['Emeishan','Buddhism','Hiking','Nature','Sacred'], difficulty: 'challenging', status: 'published', view_count: 2400, booking_count: 76 },
  ]

  const { error: tpErr } = await supabase.from('tour_plans').upsert(plans, { onConflict: 'id' })
  if (tpErr) console.log(`  ❌ ${tpErr.message}`)
  else console.log(`  ✅ ${plans.length} tour_plans`)

  // Step 4: Insert posts
  console.log('\nStep 4: Inserting posts...')
  const posts = [
    { id: 'e1a2b3c4-0001-4000-e000-000000000001', author_id: LIWEI, post_type: 'image', title: 'Sunrise at the Great Wall — Mutianyu at 5:47 AM', description: "The moment the sun breaks over the Mutianyu section, every brick glows gold. I've seen this hundreds of times and it still gives me chills. Pro tip: skip Badaling, come here. Fewer people, better views, same Wall.", media_urls: ['https://images.unsplash.com/photo-1508804185872-d7badad00f7d?w=800'], destination: 'Beijing', tags: ['Great Wall','Sunrise','Photography','Beijing'], likes_count: 3200, comments_count: 156, favorites_count: 890, shares_count: 234, view_count: 15600, status: 'published', linked_plan_id: 'f1a2b3c4-0001-4000-a000-000000000001' },
    { id: 'e1a2b3c4-0002-4000-e000-000000000002', author_id: CHENYU, post_type: 'image', title: 'Li River at dawn — the scene on your 20 yuan bill', description: "This is the exact viewpoint printed on China's 20 yuan note. But no bill can capture the mist rolling off the water at 6am, the silence broken only by cormorant fishermen. Some things you have to see with your own eyes.", media_urls: ['https://images.unsplash.com/photo-1528164344705-47542687000d?w=800'], destination: 'Guilin', tags: ['Li River','Guilin','Photography','Sunrise'], likes_count: 2890, comments_count: 134, favorites_count: 720, shares_count: 198, view_count: 13400, status: 'published', linked_plan_id: 'f1a2b3c4-0003-4000-a000-000000000003' },
    { id: 'e1a2b3c4-0003-4000-e000-000000000003', author_id: ZHANGMEI, post_type: 'image', title: 'Shanghai Bund at midnight — when the city puts on a show', description: "Every night at 7pm, Pudong lights up like a sci-fi movie. The Bund across the river is the best seat in the house. But the real magic? Finding a hidden rooftop bar where it's just you, the skyline, and a cocktail.", media_urls: ['https://images.unsplash.com/photo-1537531383496-f4749b08f3ba?w=800'], destination: 'Shanghai', tags: ['Shanghai','Bund','Nightlife','Skyline'], likes_count: 2560, comments_count: 98, favorites_count: 650, shares_count: 167, view_count: 12300, status: 'published', linked_plan_id: 'f1a2b3c4-0006-4000-a000-000000000006' },
    { id: 'e1a2b3c4-0004-4000-e000-000000000004', author_id: WANGFANG, post_type: 'image', title: "Face to face with 8,000 warriors — Xi'an Terracotta Army", description: '2,200 years ago, Emperor Qin buried an entire army to protect him in the afterlife. Each warrior has a unique face — no two are alike. Standing in Pit 1, surrounded by thousands of them, is one of the most humbling experiences on Earth.', media_urls: ['https://images.unsplash.com/photo-1555990538-1e15b0e8b558?w=800'], destination: "Xi'an", tags: ['Terracotta',"Xi'an",'History','Culture'], likes_count: 3100, comments_count: 145, favorites_count: 820, shares_count: 210, view_count: 14800, status: 'published', linked_plan_id: 'f1a2b3c4-0005-4000-a000-000000000005' },
    { id: 'e1a2b3c4-0005-4000-e000-000000000005', author_id: LIUYANG, post_type: 'image', title: 'Baby pandas at the Chengdu Research Base — impossible not to smile', description: "Every morning I watch these little furballs tumble over each other, and every morning I smile like it's the first time. Fun fact: baby pandas poop up to 40 times a day. Cute AND productive.", media_urls: ['https://images.unsplash.com/photo-1564349683136-77e08dba1ef7?w=800'], destination: 'Chengdu', tags: ['Pandas','Chengdu','Wildlife','Cute'], likes_count: 5200, comments_count: 289, favorites_count: 1400, shares_count: 345, view_count: 25600, status: 'published', linked_plan_id: 'f1a2b3c4-0007-4000-a000-000000000007' },
    { id: 'e1a2b3c4-0006-4000-e000-000000000006', author_id: ZHAOTING, post_type: 'image', title: 'West Lake at dawn — where Chinese poetry was born', description: 'Su Shi wrote about this lake 1,000 years ago: "West Lake compares to Xi Shi, always beautiful whether in light makeup or heavy." Standing here at 5:30am, mist rising, pagodas reflected — you understand exactly what he meant.', media_urls: ['https://images.unsplash.com/photo-1529240168534-2b0f59b671b0?w=800'], destination: 'Hangzhou', tags: ['West Lake','Hangzhou','Poetry','Photography'], likes_count: 2100, comments_count: 112, favorites_count: 580, shares_count: 145, view_count: 10200, status: 'published', linked_plan_id: 'f1a2b3c4-0008-4000-a000-000000000008' },
    { id: 'e1a2b3c4-0007-4000-e000-000000000007', author_id: CHENYU, post_type: 'image', title: "Longji Rice Terraces at golden hour — the Dragon's Backbone", description: "650 years ago, the Zhuang people carved these terraces into the mountains by hand. From above, they look like a dragon's scales. At golden hour, they glow like molten gold. Some views are worth every step of the climb.", media_urls: ['https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?w=800'], destination: 'Guilin', tags: ['Rice Terraces','Longji','Photography','Nature'], likes_count: 1800, comments_count: 89, favorites_count: 480, shares_count: 123, view_count: 8900, status: 'published', linked_plan_id: 'f1a2b3c4-0003-4000-a000-000000000003' },
    { id: 'e1a2b3c4-0008-4000-e000-000000000008', author_id: ZHANGMEI, post_type: 'image', title: "The perfect xiaolongbao — Shanghai's soup dumpling art", description: "18 folds. That's the standard for a proper xiaolongbao. The wrapper is thin enough to see the soup inside, thick enough to hold it. Bite the top, sip the broth, dip in black vinegar with ginger. Heaven in one bite.", media_urls: ['https://images.unsplash.com/photo-1496116218417-1a781b1c416c?w=800'], destination: 'Shanghai', tags: ['Xiaolongbao','Food','Shanghai','Dumplings'], likes_count: 4100, comments_count: 234, favorites_count: 1100, shares_count: 290, view_count: 20100, status: 'published', linked_plan_id: 'f1a2b3c4-0006-4000-a000-000000000006' },
    { id: 'e1a2b3c4-0009-4000-e000-000000000009', author_id: WANGFANG, post_type: 'image', title: 'Singing sand dunes of Dunhuang — where the desert hums', description: 'When the wind blows across Mingsha Shan, the sand sings. Literally. It produces a low humming sound that echoes across the dunes. Ride a camel at sunset, listen to the desert hum, and feel the Silk Road come alive.', media_urls: ['https://images.unsplash.com/photo-1536098561742-ca998e48cbcc?w=800'], destination: 'Dunhuang', tags: ['Dunhuang','Silk Road','Desert','Adventure'], likes_count: 2300, comments_count: 108, favorites_count: 610, shares_count: 156, view_count: 11200, status: 'published', linked_plan_id: 'f1a2b3c4-0009-4000-a000-000000000009' },
    { id: 'e1a2b3c4-0010-4000-e000-000000000010', author_id: LIUYANG, post_type: 'image', title: 'Sichuan hotpot — the meal that rewires your brain', description: 'Chili oil, Sichuan peppercorns, beef tripe, duck blood — ingredients that sound scary, taste transcendent. The numbing (ma) and spicy (la) sensation is literally addictive. Your tongue will tingle for hours. You will want more.', media_urls: ['https://images.unsplash.com/photo-1551918120-9739cb430c6d?w=800'], destination: 'Chengdu', tags: ['Hotpot','Sichuan','Food','Spicy'], likes_count: 3800, comments_count: 201, favorites_count: 980, shares_count: 267, view_count: 18700, status: 'published', linked_plan_id: 'f1a2b3c4-0007-4000-a000-000000000007' },
  ]

  const { error: postErr } = await supabase.from('posts').upsert(posts, { onConflict: 'id' })
  if (postErr) console.log(`  ❌ ${postErr.message}`)
  else console.log(`  ✅ ${posts.length} posts`)

  console.log('\n🎉 Seed data complete!')
  console.log('   6 guides | 10 tour plans | 10 posts')
}

main().catch(err => { console.error('Fatal:', err); process.exit(1) })
